### ISSUE TITLE
Error due to missing module

### ISSUE THREAD

**Issue by glennblock** [azure-contrib/socket.io-servicebus#71]
When running trying to use a fresh install of socket.io-servicebus, I am getting an error about a missing "azure-mgmt-resource" module.

```
Error: Cannot find module 'azure-mgmt-resource'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/glennblock/src/sbchat2/node_modules/socket.io-servicebus/node_modules/azure/lib/azure.js:511:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

It looks like the issue is relating to pulling in the latest azure module. If I delete the internal module and manually install an earlier version, this error goes away.

This is a blocking issue for anyone depending on this module, as the package.json for this module automatically grabs the latest azure.

**Comment by christav** [comment]
@glennblock This is actually a bug in the latest node sdk release, the package.json file is missing a required module. Will fix it there.

In the meantime it's also possible to just do an `npm install azure-mgmt-resource` and npm will do the right magic to line everything up.

**Comment by glennblock** [comment]
Thanks @christav!

**Comment by christav** [comment]
Fixed in azure node SDK.
